---
exclude: alembic|nginx
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
  - repo: https://github.com/pycqa/isort # sorts imports
    rev: 6.0.1
    hooks:
      - id: isort
        args: [ --line-length=120]
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: [ --config, pyproject.toml]
        additional_dependencies:
          - "click==8.2.1"
